# Generated by Django 2.0.7 on 2018-07-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichisblank', '0002_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='land_area_sq_km',
            field=models.IntegerField(default=455),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='population_2008',
            field=models.IntegerField(default=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='size_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
