# Generated by Django 2.0.7 on 2018-08-17 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whichisblank', '0004_comparison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='vote',
        ),
        migrations.AddField(
            model_name='selection',
            name='comparison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='whichisblank.Comparison'),
        ),
        migrations.AddField(
            model_name='selection',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_country', to='whichisblank.Country'),
        ),
    ]
